[package]
name = "clier_derive"
version = "0.1.0"
edition = "2021"
[lib]
proc-macro = true

[dependencies]
quote = "1.0.36"
syn = {version = "2.0.66", features = ["full"]}
proc-macro2 = "1.0"
attribute-derive = "0.9.1"
clier_utils = { path = "../clier_utils" }
