[package]
name = "clier"
version = "0.0.3"
edition = "2021"
authors = ["Vincent Thomas"]
description = "A command line parser and framework for rust"
license = "MIT"
repository = "https://github.com/vincent-thomas/clier"

[features]
hooks = []
default = ["hooks"]