[package]
name = "clier"
version = "0.4.0"
edition = "2021"
authors = ["Vincent Thomas"]
description = "A cli parser and framework for rust"
license = "MIT"
repository = "https://github.com/vincent-thomas/clier"
keywords = ["cli", "parser", "parse"]
documentation = "https://docs.rs/clier"

[dependencies]
serde = {version = "1.0.188", features = ["derive"]}
serde_json = "1.0.106"
thiserror = "1.0.48"

[dev-dependencies]
cargo-watch = "8.4.1"