[package]
name = "clier"
version = "0.1.0"
edition = "2021"
authors = ["Vincent Thomas"]
description = "A cli parser and framework for rust"
license = "MIT"
repository = "https://github.com/vincent-thomas/clier"

[features]
hooks = []
default = ["hooks"]