[package]
name = "clier_cli"
version = "0.6.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clier = { version = "0.6.1", path = "../clier" }
serde = "1.0.188"
serde_json = "1.0.107"
