[package]
name = "clier_parser"
version = "0.5.0"
edition = "2021"
authors = ["Vincent Thomas"]
description = "The underlying parser for the cli framework clier"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html