name: CI

on:
  push:
    branches: [ "main" ]
    tags-ignore: [ "v*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    name: Build and test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo check
    - name: Run tests
      run: cargo test --verbose

  bench:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Benchmark
      run: cargo bench
