name: Pubish

on:
  push:
    tags: [ "v*" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Build and test and publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo check
    - name: Run tests
      run: cargo test
    - name: Publish clier_parser
      run: cargo publish -p clier_parser
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}
    - name: Publish clier
      run: cargo publish -p clier
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}